name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build executable
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -S ${{ github.workspace }} -B build

    - name: Build
      run: cmake --build build
      
    - name: Upload Executable
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: plf-executable
        path: build\Debug\plf.exe

